In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [6]:
data=pd.Series(['Eswar','Dhanush','devender','Aman','priya','neha','anusha'],index=['a','b','c','d','e','f','g'])
print(data)
print(type(data))

a       Eswar
b     Dhanush
c    devender
d        Aman
e       priya
f        neha
g      anusha
dtype: object
<class 'pandas.core.series.Series'>

In [7]:
print(data['a'])

Eswar

In [8]:
d={
    "name":['Eswar','Dhanush','devender','Aman','priya','neha','anusha'],
    "id":[101,102,103,104,105,106,107],
    "age":[99,26,21,21,21,21,21]
}

In [10]:
print(d)
print(type(d))

{'name': ['Eswar', 'Dhanush', 'devender', 'Aman', 'priya', 'neha', 'anusha'], 'id': [101, 102, 103, 104, 105, 106, 107], 'age': [99, 26, 21, 21, 21, 21, 21]}
<class 'dict'>

In [12]:
data=pd.DataFrame(d)
print(data)

       name   id  age
0     Eswar  101   99
1   Dhanush  102   26
2  devender  103   21
3      Aman  104   21
4     priya  105   21
5      neha  106   21
6    anusha  107   21

In [13]:
display(data)

       name   id  age
0     Eswar  101   99
1   Dhanush  102   26
2  devender  103   21
3      Aman  104   21
4     priya  105   21
5      neha  106   21
6    anusha  107   21

In [22]:
import numpy as np
data1=pd.DataFrame({
    "name":['eswar','amandeep','dhanush'],
    "age":[23,24,np.nan],
    "placed":[np.nan,np.nan,np.nan]
})
print(data1)

       name   age  placed
0     eswar  23.0     NaN
1  amandeep  24.0     NaN
2   dhanush   NaN     NaN

In [23]:
display(data1)

       name   age  placed
0     eswar  23.0     NaN
1  amandeep  24.0     NaN
2   dhanush   NaN     NaN

In [26]:
data2=pd.read_csv("/content/Orders_2024_Jan_Jun.csv")

In [29]:
print(data2.to_string())

     OrderID   OrderDate  CustomerID CustomerName Region  ProductID ProductName     Category  Quantity  Price  TotalAmount PaymentMethod
0       1001   5/21/2024           2   Customer_2      E          9   Product_9      Grocery         9   1047         9423           UPI
1       1002   1/18/2024          37  Customer_37  North         19  Product_19   Home Decor         1   1563         1563    NetBanking
2       1003   3/28/2024           9   Customer_9  South         12  Product_12   Home Decor         4   1539         6156           COD
3       1004   3/29/2024          40  Customer_40   West         14  Product_14      Grocery         3    204          612    NetBanking
4       1005   5/25/2024          40  Customer_40   West         14  Product_14      Grocery         9    204         1836           COD
5       1006   6/28/2024          48  Customer_48      E         17  Product_17  Electronics         4   1320         5280           COD
6       1007   2/14/2024          25  Customer_25      E         18  Product_18   Home Decor         1   1099         1099          Card
7       1008   4/13/2024          30  Customer_30   West         12  Product_12   Home Decor        10   1539        15390    NetBanking
8       1009   4/22/2024           5   Customer_5   West         13  Product_13   Home Decor         6   1267         7602    NetBanking
9       1010   2/11/2024          39  Customer_39      E          5   Product_5  Electronics         1    632          632    NetBanking
10      1011   3/26/2024           7   Customer_7   West         17  Product_17  Electronics         6   1320         7920           COD
11      1012    4/5/2024          29  Customer_29   West          9   Product_9      Grocery         5   1047         5235           UPI
12      1013   5/22/2024          45  Customer_45      E          1   Product_1      Grocery         1    574          574          Card
13      1014   6/15/2024          16  Customer_16  North          8   Product_8   Home Decor         9   1924        17316           COD
14      1015   2/20/2024          17  Customer_17   West         17  Product_17  Electronics         2   1320         2640           COD
15      1016   5/29/2024          26  Customer_26      E          8   Product_8   Home Decor         8   1924        15392           COD
16      1017   4/26/2024          25  Customer_25      E          8   Product_8   Home Decor         6   1924        11544          Card
17      1018    5/5/2024           1   Customer_1  South          8   Product_8   Home Decor        10   1924        19240           UPI
18      1019   3/23/2024          16  Customer_16  North         14  Product_14      Grocery         3    204          612    NetBanking
19      1020    4/5/2024          31  Customer_31  South          2   Product_2   Home Decor         7    481         3367    NetBanking
20      1021   3/15/2024          38  Customer_38  North          8   Product_8   Home Decor         1   1924         1924           UPI
21      1022    3/3/2024          28  Customer_28  North          4   Product_4      Grocery        10   1380        13800           COD
22      1023   6/24/2024          35  Customer_35      E          9   Product_9      Grocery         2   1047         2094          Card
23      1024    1/5/2024          46  Customer_46  South         16  Product_16  Electronics        10   1948        19480           UPI
24      1025   3/11/2024          12  Customer_12  South          9   Product_9      Grocery         6   1047         6282           COD
25      1026   5/15/2024          48  Customer_48      E          8   Product_8   Home Decor         6   1924        11544    NetBanking
26      1027   4/18/2024           4   Customer_4  North          2   Product_2   Home Decor         4    481         1924           UPI
27      1028   2/16/2024          21  Customer_21   West         14  Product_14      Grocery         7    204         1428          Card
28      1029    2/4/2024          27  Customer_27   West         16  Product_16  Electronics         5   1948         9740          Card
29      1030    3/6/2024          36  Customer_36  South         19  Product_19   Home Decor         4   1563         6252    NetBanking
30      1031   4/12/2024           5   Customer_5   West         10  Product_10      Fashion         8    273         2184    NetBanking
31      1032   5/20/2024           5   Customer_5   West         14  Product_14      Grocery         9    204         1836    NetBanking
32      1033   2/28/2024          40  Customer_40   West         13  Product_13   Home Decor         6   1267         7602    NetBanking
33      1034   1/24/2024          16  Customer_16  North         14  Product_14      Grocery         2    204          408           UPI
34      1035   6/12/2024          48  Customer_48   East          2   Product_2   Home Decor         3    481         1443          Card
35      1036   6/27/2024          10  Customer_10  North         15  Product_15      Grocery        10    976         9760    NetBanking
36      1037   5/24/2024          49  Customer_49   West          7   Product_7      Fashion         3   1625         4875    NetBanking
37      1038    5/2/2024          23  Customer_23   West          8   Product_8   Home Decor         4   1924         7696          Card
38      1039   5/23/2024           7   Customer_7   West          5   Product_5  Electronics         1    632          632           COD
39      1040    1/5/2024          22  Customer_22  South         17  Product_17  Electronics         2   1320         2640    NetBanking
40      1041   5/28/2024           6   Customer_6   West          6   Product_6      Fashion        10   1421        14210           COD
41      1042   5/16/2024          15  Customer_15   West          8   Product_8   Home Decor         4   1924         7696          Card
42      1043   5/15/2024          44  Customer_44  North         15  Product_15      Grocery         3    976         2928           COD
43      1044   3/30/2024           8   Customer_8  North         12  Product_12   Home Decor        10   1539        15390    NetBanking
44      1045   6/11/2024          46  Customer_46  South         19  Product_19   Home Decor         2   1563         3126           COD
45      1046    3/6/2024          34  Customer_34  North         15  Product_15      Grocery         5    976         4880          Card
46      1047    1/7/2024          46  Customer_46  South         13  Product_13   Home Decor         7   1267         8869           UPI
47      1048    3/3/2024          43  Customer_43  South          9   Product_9      Grocery         2   1047         2094           COD
48      1049   6/13/2024           6   Customer_6   West         11  Product_11      Grocery         5   1093         5465    NetBanking
49      1050   1/15/2024          36  Customer_36  South          4   Product_4      Grocery         4   1380         5520          Card
50      1051   5/15/2024          43  Customer_43  South         16  Product_16  Electronics         6   1948        11688          Card
51      1052    6/3/2024          38  Customer_38  North         11  Product_11      Grocery         4   1093         4372          Card
52      1053   5/28/2024          49  Customer_49   West         12  Product_12   Home Decor         1   1539         1539          Card
53      1054   1/20/2024          45  Customer_45   East          2   Product_2   Home Decor         8    481         3848          Card
54      1055   1/11/2024           8   Customer_8  North          5   Product_5  Electronics         2    632         1264           COD
55      1056    4/8/2024          22  Customer_22  South          1   Product_1      Grocery         5    574         2870           COD
56      1057   1/26/2024          35  Customer_35   East         16  Product_16  Electronics         1   1948         1948    NetBanking
57      1058   4/19/2024          32  Customer_32   West         15  Product_15      Grocery         4    976         3904    NetBanking
58      1059   6/10/2024           6   Customer_6   West         12  Product_12   Home Decor         5   1539         7695           COD
59      1060   2/15/2024          26  Customer_26   East         16  Product_16  Electronics         6   1948        11688    NetBanking
60      1061   3/11/2024          23  Customer_23   West          8   Product_8   Home Decor         7   1924        13468           UPI
61      1062   5/31/2024          33  Customer_33  North          5   Product_5  Electronics        10    632         6320           UPI
62      1063   6/30/2024          44  Customer_44  North         20  Product_20  Electronics         5   1558         7790           COD
63      1064   6/26/2024          21  Customer_21   West          3   Product_3  Electronics        10   1214        12140    NetBanking
64      1065    5/3/2024          16  Customer_16  North         10  Product_10      Fashion         3    273          819          Card
65      1066   5/16/2024          28  Customer_28  North         13  Product_13   Home Decor         6   1267         7602           COD
66      1067    6/6/2024          38  Customer_38  North          8   Product_8   Home Decor         6   1924        11544    NetBanking
67      1068   4/20/2024          38  Customer_38  North         18  Product_18   Home Decor         3   1099         3297    NetBanking
68      1069    4/2/2024          39  Customer_39   East         15  Product_15      Grocery         5    976         4880    NetBanking
69      1070   3/15/2024          24  Customer_24   West         12  Product_12   Home Decor         6   1539         9234          Card
70      1071    2/4/2024           8   Customer_8  North         13  Product_13   Home Decor        10   1267        12670          Card
71      1072   1/27/2024          19  Customer_19      S          2   Product_2   Home Decor         1    481          481          Card
72      1073    4/7/2024          47  Customer_47   West          3   Product_3  Electronics         5   1214         6070           COD
73      1074   3/18/2024          26  Customer_26   East          7   Product_7      Fashion         6   1625         9750          Card
74      1075   4/28/2024          23  Customer_23   West         18  Product_18   Home Decor         8   1099         8792           COD
75      1076   4/27/2024          49  Customer_49   West          3   Product_3  Electronics         8   1214         9712          Card
76      1077    2/7/2024          40  Customer_40   West         12  Product_12   Home Decor         6   1539         9234           UPI
77      1078   3/31/2024           8   Customer_8  North         20  Product_20  Electronics         8   1558        12464           UPI
78      1079    5/1/2024          19  Customer_19      S         16  Product_16  Electronics         2   1948         3896          Card
79      1080   2/20/2024          15  Customer_15   West          1   Product_1      Grocery         5    574         2870          Card
80      1081    6/5/2024          12  Customer_12      S         12  Product_12   Home Decor         1   1539         1539          Card
81      1082   6/19/2024           5   Customer_5   West          2   Product_2   Home Decor         1    481          481           UPI
82      1083   4/27/2024           1   Customer_1      S          5   Product_5  Electronics        10    632         6320    NetBanking
83      1084   2/13/2024          36  Customer_36      S          4   Product_4      Grocery         5   1380         6900          Card
84      1085   3/19/2024          50  Customer_50      S          3   Product_3  Electronics         6   1214         7284          Card
85      1086   3/25/2024          47  Customer_47   West         16  Product_16  Electronics         5   1948         9740          Card
86      1087   2/16/2024          26  Customer_26   East          2   Product_2   Home Decor         2    481          962           COD
87      1088   5/14/2024           2   Customer_2   East          1   Product_1      Grocery        10    574         5740           COD
88      1089   5/12/2024          43  Customer_43      S         13  Product_13   Home Decor        10   1267        12670    NetBanking
89      1090    5/7/2024          48  Customer_48   East         10  Product_10      Fashion         4    273         1092          Card
90      1091   2/29/2024          47  Customer_47   West          9   Product_9      Grocery         4   1047         4188           COD
91      1092   3/17/2024          48  Customer_48   East          6   Product_6      Fashion         7   1421         9947           UPI
92      1093   3/13/2024          19  Customer_19      S         17  Product_17  Electronics         4   1320         5280          Card
93      1094    1/4/2024          46  Customer_46      S         19  Product_19   Home Decor        10   1563        15630          Card
94      1095   3/16/2024          39  Customer_39   East          1   Product_1      Grocery         9    574         5166    NetBanking
95      1096   1/20/2024          19  Customer_19      S         14  Product_14      Grocery         9    204         1836    NetBanking
96      1097   6/26/2024          15  Customer_15   West          4   Product_4      Grocery         2   1380         2760           COD
97      1098   3/16/2024          13  Customer_13   East         14  Product_14      Grocery         2    204          408    NetBanking
98      1099   2/15/2024          44  Customer_44  North          2   Product_2   Home Decor         9    481         4329           UPI
99      1100   2/10/2024           3   Customer_3  North         14  Product_14      Grocery         4    204          816           UPI
100     1101   2/17/2024          39  Customer_39   East          8   Product_8   Home Decor         2   1924         3848           COD
101     1102    3/2/2024          23  Customer_23   West          8   Product_8   Home Decor         8   1924        15392           UPI
102     1103   5/12/2024          26  Customer_26   East         17  Product_17  Electronics         7   1320         9240           COD
103     1104    2/9/2024          17  Customer_17   West         19  Product_19   Home Decor         5   1563         7815          Card
104     1105    4/8/2024          44  Customer_44  North          2   Product_2   Home Decor         9    481         4329    NetBanking
105     1106   1/28/2024           5   Customer_5   West          4   Product_4      Grocery         1   1380         1380           COD
106     1107    4/7/2024          25  Customer_25   East         19  Product_19   Home Decor         7   1563        10941           COD
107     1108    3/1/2024          43  Customer_43  South          1   Product_1      Grocery         5    574         2870    NetBanking
108     1109   1/23/2024          50  Customer_50  South         16  Product_16  Electronics         1   1948         1948           COD
109     1110   4/30/2024          27  Customer_27   West         10  Product_10      Fashion         8    273         2184    NetBanking
110     1111   4/27/2024          19  Customer_19  South         13  Product_13   Home Decor        10   1267        12670           UPI
111     1112   1/21/2024          10  Customer_10  North         14  Product_14      Grocery         9    204         1836           UPI
112     1113   3/28/2024          44  Customer_44  North          8   Product_8   Home Decor         8   1924        15392          Card
113     1114   5/18/2024          21  Customer_21      W          3   Product_3  Electronics         2   1214         2428    NetBanking
114     1115   5/14/2024          33  Customer_33  North         12  Product_12   Home Decor         7   1539        10773    NetBanking
115     1116    2/4/2024           1   Customer_1  South          9   Product_9      Grocery         9   1047         9423           COD
116     1117    5/4/2024          24  Customer_24      W          7   Product_7      Fashion         3   1625         4875           UPI
117     1118   6/12/2024          38  Customer_38  North          1   Product_1      Grocery         3    574         1722           COD
118     1119   2/15/2024          23  Customer_23      W          8   Product_8   Home Decor         2   1924         3848          Card
119     1120    3/2/2024          29  Customer_29      W         10  Product_10      Fashion        10    273         2730           UPI
120     1121    3/7/2024          45  Customer_45   East         17  Product_17  Electronics        10   1320        13200           UPI
121     1122   5/26/2024          43  Customer_43  South         16  Product_16  Electronics         3   1948         5844          Card
122     1123    2/5/2024          50  Customer_50  South         15  Product_15      Grocery        10    976         9760           UPI
123     1124    4/9/2024          47  Customer_47      W          4   Product_4      Grocery         1   1380         1380    NetBanking
124     1125   4/27/2024          39  Customer_39   East         16  Product_16  Electronics         5   1948         9740    NetBanking
125     1126   6/21/2024           3   Customer_3  North         17  Product_17  Electronics         8   1320        10560           UPI
126     1127    3/4/2024          46  Customer_46  South          5   Product_5  Electronics         5    632         3160           UPI
127     1128   1/10/2024          29  Customer_29   West          9   Product_9      Grocery         7   1047         7329           COD
128     1129   1/11/2024          16  Customer_16  North         14  Product_14      Grocery         7    204         1428          Card
129     1130    4/2/2024          14  Customer_14  South         15  Product_15      Grocery         5    976         4880           COD
130     1131   5/22/2024          11  Customer_11   West          1   Product_1      Grocery         9    574         5166          Card
131     1132    6/5/2024          48  Customer_48   East          8   Product_8   Home Decor         6   1924        11544          Card
132     1133    6/6/2024          32  Customer_32   West         15  Product_15      Grocery         1    976          976           UPI
133     1134   2/22/2024          30  Customer_30   West          5   Product_5  Electronics         4    632         2528          Card
134     1135   5/10/2024          40  Customer_40   West          2   Product_2   Home Decor         4    481         1924          Card
135     1136   3/14/2024          24  Customer_24   West         12  Product_12   Home Decor         7   1539        10773          Card
136     1137   5/29/2024          32  Customer_32   West         16  Product_16  Electronics        10   1948        19480           COD
137     1138    2/2/2024          38  Customer_38  North          2   Product_2   Home Decor         2    481          962           COD
138     1139   4/15/2024           1   Customer_1  South          7   Product_7      Fashion         6   1625         9750    NetBanking
139     1140   1/20/2024          43  Customer_43  South         17  Product_17  Electronics         4   1320         5280          Card
140     1141   2/28/2024          15  Customer_15   West          3   Product_3  Electronics         4   1214         4856           COD
141     1142    4/1/2024          50  Customer_50  South          1   Product_1      Grocery         1    574          574          Card
142     1143   5/31/2024          14  Customer_14  South          6   Product_6      Fashion         1   1421         1421           UPI
143     1144   5/23/2024          21  Customer_21   West         20  Product_20  Electronics         9   1558        14022    NetBanking

In [28]:
display(data2)

,OrderID,OrderDate,CustomerID,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
0,1001,5/21/2024,2,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI
1,1002,1/18/2024,37,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking
2,1003,3/28/2024,9,Customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD
3,1004,3/29/2024,40,Customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking
4,1005,5/25/2024,40,Customer_40,West,14,Product_14,Grocery,9,204,1836,COD
...,...,...,...,...,...,...,...,...,...,...,...,...
265,1020,4/5/2024,31,Customer_31,South,2,Product_2,Home Decor,7,481,3367,NetBanking
266,1021,3/15/2024,38,Customer_38,North,8,Product_8,Home Decor,1,1924,1924,UPI
267,1022,3/3/2024,28,Customer_28,North,4,Product_4,Grocery,10,1380,13800,COD
268,1023,6/24/2024,35,Customer_35,East,9,Product_9,Grocery,2,1047,2094,Card
269,1024,1/5/2024,46,Customer_46,South,16,Product_16,Electronics,10,1948,19480,UPI

In [31]:
data3=pd.read_excel("/content/eco.xlsx")
print(data3.to_string())

     Order ID  Customer Name         City City Code  Order Amount ($) Order Date
0  ORDNYC0001     John Smith     New York       NYC               250 2026-01-05
1  ORDLAX0002   Emma Johnson  Los Angeles       LAX               180 2026-01-06
2  ORDCHI0003     Liam Brown      Chicago       CHI               320 2026-01-07
3  ORDHOU0004   Olivia Davis      Houston       HOU               145 2026-01-08
4  ORDPHX0005    Noah Wilson      Phoenix       PHX               500 2026-01-09
5  ORDNYC0006   Ava Martinez     New York       NYC               275 2026-01-10
6  ORDLAX0007    William Lee  Los Angeles       LAX               390 2026-01-11
7  ORDCHI0008   Sophia Clark      Chicago       CHI               210 2026-01-12
8  ORDHOU0009    James Lewis      Houston       HOU               175 2026-01-13
9  ORDPHX0010  Isabella Hall      Phoenix       PHX               420 2026-01-14

In [32]:
display(data3)

,Order ID,Customer Name,City,City Code,Order Amount ($),Order Date
0,ORDNYC0001,John Smith,New York,NYC,250,2026-01-05
1,ORDLAX0002,Emma Johnson,Los Angeles,LAX,180,2026-01-06
2,ORDCHI0003,Liam Brown,Chicago,CHI,320,2026-01-07
3,ORDHOU0004,Olivia Davis,Houston,HOU,145,2026-01-08
4,ORDPHX0005,Noah Wilson,Phoenix,PHX,500,2026-01-09
5,ORDNYC0006,Ava Martinez,New York,NYC,275,2026-01-10
6,ORDLAX0007,William Lee,Los Angeles,LAX,390,2026-01-11
7,ORDCHI0008,Sophia Clark,Chicago,CHI,210,2026-01-12
8,ORDHOU0009,James Lewis,Houston,HOU,175,2026-01-13
9,ORDPHX0010,Isabella Hall,Phoenix,PHX,420,2026-01-14