In [3]:
import pandas as pd
import numpy as np

In [4]:
data=pd.Series(['jain','ramana','neha','anusha'])
print(data)
print(type(data))

0      jain
1    ramana
2      neha
3    anusha
dtype: object
<class 'pandas.core.series.Series'>

In [10]:
d={
    'name':['jain','ramana','neha','anusha','akshaya','akhil','priya'],
    'age':[23,21,np.nan,np.nan,np.nan,88,np.nan]
}

In [11]:
data1=pd.DataFrame(d)

In [12]:
print(data1)

      name   age
0     jain  23.0
1   ramana  21.0
2     neha   NaN
3   anusha   NaN
4  akshaya   NaN
5    akhil  88.0
6    priya   NaN

In [13]:
print(type(data1))

<class 'pandas.core.frame.DataFrame'>

In [16]:
display(data1.head())

      name   age
0     jain  23.0
1   ramana  21.0
2     neha   NaN
3   anusha   NaN
4  akshaya   NaN

In [17]:
display(data1.head(2))

     name   age
0    jain  23.0
1  ramana  21.0

In [18]:
display(data1.tail())

      name   age
2     neha   NaN
3   anusha   NaN
4  akshaya   NaN
5    akhil  88.0
6    priya   NaN

In [19]:
display(data1.tail(3))

      name   age
4  akshaya   NaN
5    akhil  88.0
6    priya   NaN

In [20]:
display(data1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    7 non-null      object
 1   age     3 non-null      float64
dtypes: float64(1), object(1)
memory usage: 244.0+ bytes

None

In [21]:
display(data1['name'].info())

<class 'pandas.core.series.Series'>
RangeIndex: 7 entries, 0 to 6
Series name: name
Non-Null Count  Dtype
--------------  -----
7 non-null      object
dtypes: object(1)
memory usage: 188.0+ bytes

None

In [22]:
display(data1.describe())

             age
count   3.000000
mean   44.000000
std    38.118237
min    21.000000
25%    22.000000
50%    23.000000
75%    55.500000
max    88.000000

In [23]:
print(data1.shape)

(7, 2)

In [24]:
print(data1.dtypes)

name     object
age     float64
dtype: object

In [25]:
print(data1.memory_usage())

Index    132
name      56
age       56
dtype: int64

In [26]:
data=pd.read_csv("/content/ecommerce_dirty_data.csv")

In [28]:
print(data.to_string())

     order_id firstname lastname                   email     product  quantity    price       city state   pincode order_date payment_method     status
0        1001      Sita    Reddy    sita.reddy@email.com      Camera       2.0   1500.0    Chennai    WB  500001.0  1/15/2025    Credit Card  Cancelled
1        1002      Sita     Nair                     NaN       Mouse       1.0   2000.0  Bangalore    DL  600001.0  1/12/2025            NaN  Cancelled
2        1003     Kiran    Mehta   kiran.mehta@email.com    Keyboard       1.0  55000.0      Delhi    TS  500001.0  1/19/2025            COD  Cancelled
3        1004     Kiran    Singh   kiran.singh@email.com      Camera       2.0   2000.0    Kolkata    MH  380001.0  1/18/2025            COD    Pending
4        1005     Rahul     Nair    rahul.nair@email.com    Keyboard       2.0      NaN  Ahmedabad    GJ  380001.0  1/18/2025     NetBanking  Cancelled
5        1006     Pooja    Verma   pooja.verma@email.com      Mobile       1.0  30000.0     Mumbai    TN  110001.0  1/16/2025     NetBanking    Pending
6        1007     Rahul      Das     rahul.das@email.com     Charger       1.0   1500.0     Mumbai    TN  400001.0  1/18/2025            NaN   Returned
7        1008     Sneha    Verma   sneha.verma@email.com      Laptop       NaN      NaN  Hyderabad    MH  380001.0  1/20/2025            Upi    Pending
8        1009      Anil      Das      anil.das@email.com     Charger       NaN  30000.0    Kolkata    WB  560001.0  1/11/2025            NaN   Returned
9        1010      Sita     Nair     sita.nair@email.com  Headphones       1.0   2000.0     Mumbai    TN       NaN  1/14/2025     NetBanking  Delivered
10       1011     Vikas    Patel   vikas.patel@email.com      Tablet       2.0   2000.0    Kolkata    GJ  380001.0  1/13/2025            NaN  Delivered
11       1012     Priya    Kumar   priya.kumar@email.com  Headphones       2.0  30000.0     Mumbai    MH  500001.0  1/16/2025     NetBanking   Returned
12       1013      Sita    Singh    sita.singh@email.com       Mouse       1.0  30000.0      Delhi    GJ  600001.0  1/14/2025            COD  Delivered
13       1014     Priya    Reddy   priya.reddy@email.com      Camera       1.0      NaN        NaN    TN  110001.0  1/18/2025            COD   Returned
14       1015     Sneha    Verma   sneha.verma@email.com       Mouse       2.0  30000.0       Pune    TS  110001.0  1/10/2025            NaN   Returned
15       1016      Amit   Sharma   amit.sharma@email.com    Keyboard       NaN  55000.0  Bangalore    MH  400001.0  1/17/2025    Credit Card  Delivered
16       1017     Kiran   Sharma  kiran.sharma@email.com    Keyboard       3.0   1500.0    Chennai    WB  560001.0  1/10/2025            Upi    Pending
17       1018     Rahul    Verma   rahul.verma@email.com     Charger       3.0  55000.0  Bangalore    MH  110001.0  1/20/2025            Upi   Returned
18       1019     Pooja   Sharma  pooja.sharma@email.com  Headphones       1.0   2000.0        NaN    WB  380001.0  1/17/2025     NetBanking  Delivered
19       1020      Anil    Singh    anil.singh@email.com      Laptop       3.0   1500.0      Delhi    KA  560001.0  1/11/2025     NetBanking   Returned
20       1021     Rahul    Kumar   rahul.kumar@email.com      Mobile       3.0   2000.0        Hyd    GJ  380001.0  1/17/2025    Credit Card  Delivered
21       1022      Amit    Verma    amit.verma@email.com    Keyboard       2.0  30000.0     Mumbai    GJ  110001.0  1/13/2025            Upi    Pending
22       1023     Sneha    Verma                     NaN      Tablet       NaN  30000.0       Pune    KA  400001.0  1/15/2025            Upi    Pending
23       1024     Pooja   Sharma  pooja.sharma@email.com      Camera       1.0      NaN    Chennai    KA  560001.0  1/18/2025            Upi  Delivered
24       1025     Kiran    Mehta   kiran.mehta@email.com      Tablet       3.0  30000.0     Mumbai    GJ  500001.0  1/15/2025            COD  Delivered
25       1026      Anil    Reddy    anil.reddy@email.com  Headphones       2.0   2000.0    Kolkata    GJ  400001.0  1/15/2025     NetBanking  Delivered
26       1027      Sita   Sharma   sita.sharma@email.com      Laptop       2.0  55000.0       Pune    DL       NaN  1/15/2025            COD  Cancelled
27       1028      Sita    Mehta    sita.mehta@email.com     Charger       1.0   1500.0  Bangalore    WB  380001.0  1/14/2025            Upi  Delivered
28       1029     Sneha    Reddy   sneha.reddy@email.com      Laptop       1.0   1500.0       Pune    TS       NaN  1/18/2025     NetBanking  Delivered
29       1030      Amit    Patel                     NaN     Charger       1.0      NaN  Ahmedabad    TS  560001.0  1/10/2025    Credit Card  Cancelled
30       1031     Vikas    Kumar   vikas.kumar@email.com      Tablet       3.0  55000.0     Mumbai    DL  500001.0  1/16/2025            COD    Pending
31       1032     Priya     Nair    priya.nair@email.com       Mouse       2.0      NaN    Kolkata    TS  600001.0  1/16/2025            NaN   Returned
32       1033     Priya    Patel   priya.patel@email.com    Keyboard       NaN   1500.0      Delhi    TS  380001.0  1/19/2025            COD  Delivered
33       1034     Rahul    Kumar   rahul.kumar@email.com     Charger       NaN   2000.0      Delhi    GJ  560001.0  1/13/2025            Upi  Delivered
34       1035     Priya    Gupta                     NaN      Tablet       3.0  30000.0       Pune    KA  380001.0  1/19/2025    Credit Card  Delivered
35       1036      Anil    Gupta    anil.gupta@email.com      Camera       3.0  30000.0      Delhi    MH       NaN  1/11/2025            COD    Pending
36       1037      Amit    Verma    amit.verma@email.com      Tablet       1.0      NaN      Delhi    TS  110001.0  1/14/2025            NaN   Returned
37       1038      Ravi    Mehta    ravi.mehta@email.com    Keyboard       3.0  30000.0  Ahmedabad    TN  560001.0  1/15/2025     NetBanking   Returned
38       1039      Amit      Das      amit.das@email.com      Camera       2.0  30000.0  Ahmedabad    TN  560001.0  1/18/2025            COD  Delivered
39       1040      Anil    Gupta    anil.gupta@email.com      Mobile       NaN  30000.0      Delhi    GJ  600001.0  1/14/2025            Upi  Cancelled
40       1041      Sita    Singh    sita.singh@email.com  Headphones       1.0   1500.0        Hyd    TS  560001.0  1/11/2025    Credit card    Pending
41       1042     Sneha      Das     sneha.das@email.com  Headphones       1.0   1500.0    Chennai    KA  400001.0  1/15/2025    Credit card  Cancelled
42       1043      Amit     Nair     amit.nair@email.com      Mobile       2.0   2000.0        NaN    TS  600001.0  1/15/2025            COD    Pending
43       1044     Kiran    Gupta   kiran.gupta@email.com      Tablet       3.0  55000.0        NaN    KA  110001.0  1/14/2025    Credit card   Returned
44       1045     Pooja   Sharma  pooja.sharma@email.com    Keyboard       NaN  30000.0  Ahmedabad    TS  500001.0  1/10/2025    Credit card  Cancelled
45       1046      Amit    Kumar    amit.kumar@email.com  Headphones       NaN      NaN      Delhi    TS  500001.0  1/16/2025     NetBanking    Pending
46       1047     Priya      Das     priya.das@email.com      Mobile       1.0   2000.0     Mumbai    WB  380001.0  1/16/2025     NetBanking  Delivered
47       1048      Anil    Kumar    anil.kumar@email.com  Headphones       3.0  55000.0        Hyd    WB  500001.0  1/20/2025            UPI   Returned
48       1049      Amit      Das      amit.das@email.com     Charger       NaN      NaN  Ahmedabad    MH  600001.0  1/19/2025    Credit card  Delivered
49       1050      Anil    Mehta    anil.mehta@email.com      Laptop       3.0      NaN    Kolkata    WB  600001.0  1/18/2025     NetBanking  Cancelled
50       1051      Anil     Nair     anil.nair@email.com     Charger       NaN  30000.0     Mumbai    MH  560001.0  1/15/2025            NaN  Delivered
51       1052      Sita    Gupta                     NaN       Mouse       2.0      NaN     Mumbai    MH  110001.0  1/14/2025     NetBanking   Returned
52       1053      Ravi    Singh    ravi.singh@email.com     Charger       3.0  55000.0      Delhi    WB       NaN  1/18/2025    Credit card    Pending
53       1054     Rahul    Patel                     NaN      Tablet       3.0      NaN        NaN    GJ  560001.0  1/20/2025     NetBanking   Returned
54       1055     Priya      Das     priya.das@email.com       Mouse       2.0   1500.0       Pune    WB  600001.0  1/16/2025            NaN  Cancelled
55       1056      Amit     Nair                     NaN    Keyboard       3.0  55000.0  Bangalore    GJ  500001.0  1/10/2025    Credit card  Cancelled
56       1057      Anil    Verma                     NaN  Headphones       NaN  30000.0      Delhi    KA  400001.0  1/16/2025            COD  Cancelled
57       1058      Sita    Mehta    sita.mehta@email.com  Headphones       2.0   1500.0      Delhi    MH  380001.0  1/19/2025     NetBanking   Returned
58       1059     Kiran      Das     kiran.das@email.com    Keyboard       NaN  30000.0       Pune    TS  110001.0  1/11/2025            COD  Delivered
59       1060     Rahul    Kumar   rahul.kumar@email.com      Laptop       1.0  30000.0  Bangalore    GJ  400001.0  1/11/2025            UPI  Delivered
60       1061      Ravi      Das      ravi.das@email.com      Camera       3.0   2000.0     Mumbai    GJ  500001.0  1/20/2025    Credit card    Pending
61       1062      Ravi    Kumar                     NaN      Camera       3.0   1500.0  Hyderabad    MH  400001.0  1/14/2025    Credit Card    Pending
62       1063     Vikas    Singh   vikas.singh@email.com      Mobile       NaN      NaN    Chennai    DL  110001.0  1/13/2025            COD    Pending
63       1064      Anil    Gupta    anil.gupta@email.com      Laptop       1.0  30000.0      Delhi    TS  110001.0  1/12/2025            COD  Cancelled
64       1065     Pooja    Singh   pooja.singh@email.com       Mouse       1.0   1500.0  Bangalore    WB  500001.0  1/18/2025            COD    Pending
65       1066     Pooja    Verma   pooja.verma@email.com      Mobile       2.0      NaN       Pune    MH       NaN  1/12/2025    Credit Card  Delivered
66       1067     Priya    Singh                     NaN      Camera       3.0  30000.0       Pune    GJ  560001.0  1/12/2025     NetBanking  Delivered
67       1068      Sita    Kumar    sita.kumar@email.com      Camera       1.0  30000.0    Kolkata    GJ  380001.0  1/11/2025            NaN  Delivered
68       1069     Vikas   Sharma  vikas.sharma@email.com       Mouse       3.0  55000.0  Hyderabad    MH  560001.0  1/16/2025     NetBanking   Returned
69       1070      Ravi    Reddy    ravi.reddy@email.com      Laptop       1.0  55000.0  Ahmedabad    KA  560001.0  1/17/2025     NetBanking   Returned
70       1071     Kiran    Kumar   kiran.kumar@email.com       Mouse       3.0  30000.0  Ahmedabad    DL  500001.0  1/10/2025            UPI  Cancelled
71       1072      Ravi    Mehta    ravi.mehta@email.com      Camera       3.0  30000.0      Delhi    TN  560001.0  1/15/2025     NetBanking  Delivered
72       1073      Ravi     Nair     ravi.nair@email.com     Charger       2.0  55000.0       Pune    MH  560001.0  1/18/2025            COD    Pending
73       1074      Sita      Das      sita.das@email.com      Mobile       NaN      NaN        NaN    MH  560001.0  1/10/2025     NetBanking  Delivered
74       1075     Vikas    Kumar   vikas.kumar@email.com    Keyboard       2.0  30000.0        NaN    KA  560001.0  1/15/2025            COD    Pending
75       1076      Amit    Patel    amit.patel@email.com      Laptop       3.0  30000.0  Bangalore    TS  500001.0  1/10/2025    Credit Card   Returned
76       1077     Priya    Patel   priya.patel@email.com  Headphones       2.0  30000.0        NaN    TN  560001.0  1/14/2025     NetBanking  Delivered
77       1078     Priya    Singh   priya.singh@email.com    Keyboard       NaN  30000.0       Pune    MH  560001.0  1/16/2025    Credit Card   Returned
78       1079     Pooja    Patel   pooja.patel@email.com      Mobile       3.0   1500.0     Mumbai    DL  500001.0  1/15/2025            NaN  Cancelled
79       1080      Amit    Mehta    amit.mehta@email.com      Camera       2.0   1500.0    Chennai    TN  400001.0  1/17/2025            COD  Cancelled
80       1081      Anil    Mehta    anil.mehta@email.com      Camera       NaN  55000.0  Ahmedabad    TN  400001.0  1/17/2025     NetBanking  Delivered
81       1082     Vikas    Mehta   vikas.mehta@email.com      Laptop       NaN   1500.0  Hyderabad    GJ  600001.0  1/20/2025            NaN   Returned
82       1083     Rahul   Sharma  rahul.sharma@email.com    Keyboard       2.0   2000.0     Mumbai    TS  380001.0  1/17/2025            NaN   Returned
83       1084     Pooja    Singh   pooja.singh@email.com  Headphones       3.0      NaN       Bang    TN  400001.0  1/19/2025    Credit Card    Pending
84       1085      Anil    Patel    anil.patel@email.com      Mobile       3.0  30000.0       Bang    DL  600001.0  1/11/2025    Credit Card   Returned
85       1086     Pooja    Patel   pooja.patel@email.com    Keyboard       1.0  55000.0    Chennai    MH  110001.0  1/15/2025            COD    Pending
86       1087     Kiran    Verma   kiran.verma@email.com      Mobile       NaN   1500.0       Bang    WB  560001.0  1/20/2025            UPI   Returned
87       1088      Sita    Kumar    sita.kumar@email.com      Mobile       1.0  55000.0  Hyderabad    MH  380001.0  1/11/2025    Credit Card   Returned
88       1089     Sneha    Singh                     NaN    Keyboard       NaN  30000.0      Delhi    MH  600001.0  1/16/2025            COD   Returned
89       1090      Amit    Mehta    amit.mehta@email.com     Charger       2.0      NaN  Ahmedabad    TS  380001.0  1/15/2025    Credit Card  Cancelled
90       1091     Pooja    Kumar   pooja.kumar@email.com       Mouse       2.0      NaN    Kolkata    TN  560001.0  1/15/2025            COD  Delivered
91       1092      Anil    Mehta    anil.mehta@email.com  Headphones       2.0   1500.0        NaN    KA  380001.0  1/20/2025            UPI  Cancelled
92       1093     Kiran   Sharma  kiran.sharma@email.com     Charger       NaN   1500.0       Bang    DL  110001.0  1/17/2025            COD    Pending
93       1094     Kiran    Kumar   kiran.kumar@email.com      Tablet       1.0  30000.0       Pune    TN  110001.0  1/19/2025            COD  Delivered
94       1095      Sita    Kumar    sita.kumar@email.com      Tablet       NaN   2000.0        NaN    KA  400001.0  1/14/2025            NaN   Returned
95       1096     Kiran    Reddy   kiran.reddy@email.com    Keyboard       NaN  30000.0  Hyderabad    WB  500001.0  1/14/2025            COD    Pending
96       1097     Kiran    Kumar                     NaN      Tablet       1.0  55000.0    Kolkata    TS  560001.0  1/20/2025            COD    Pending
97       1098     Kiran    Reddy   kiran.reddy@email.com     Charger       3.0  55000.0  Ahmedabad    MH       NaN  1/17/2025            NaN    Pending
98       1099      Amit    Verma    amit.verma@email.com      Camera       1.0  30000.0       Bang    WB  380001.0  1/20/2025            UPI  Delivered
99       1100     Sneha   Sharma  sneha.sharma@email.com      Laptop       3.0  55000.0  Bangalore    GJ  600001.0  1/11/2025     NetBanking   Returned
100      1101     Priya    Patel   priya.patel@email.com      Tablet       NaN   2000.0     Mumbai    DL  110001.0  1/10/2025            NaN   Returned
101      1102     Pooja    Reddy   pooja.reddy@email.com       Mouse       1.0      NaN        NaN    TN  560001.0  1/13/2025            COD  Cancelled
102      1103     Sneha    Mehta   sneha.mehta@email.com    Keyboard       3.0   1500.0  Bangalore    WB  500001.0  1/12/2025            UPI  Delivered
103      1104      Sita    Verma    sita.verma@email.com      Laptop       3.0  55000.0  Hyderabad    KA       NaN  1/13/2025    Credit Card    Pending
104      1105      Anil   Sharma   anil.sharma@email.com      Laptop       1.0   1500.0  Bangalore    MH  400001.0  1/11/2025            COD    Pending
105      1106     Vikas    Kumar   vikas.kumar@email.com      Laptop       3.0      NaN    Kolkata    TN  500001.0  1/12/2025     NetBanking  Delivered
106      1107     Kiran   Sharma                     NaN      Camera       2.0   2000.0    Kolkata    TN  600001.0  1/20/2025            NaN    Pending
107      1108     Vikas      Das     vikas.das@email.com      Camera       3.0  55000.0    Chennai    KA  380001.0  1/19/2025     NetBanking    Pending
108      1109      Amit   Sharma   amit.sharma@email.com      Laptop       3.0      NaN  Bangalore    TN  400001.0  1/14/2025     NetBanking   Returned
109      1110      Amit    Patel    amit.patel@email.com      Mobile       NaN   2000.0    Kolkata    MH  380001.0  1/11/2025            NaN  Delivered
110      1111     Pooja    Patel   pooja.patel@email.com     Charger       3.0   2000.0  Hyderabad    DL  560001.0  1/14/2025            NaN    Pending
111      1112     Rahul    Mehta   rahul.mehta@email.com    Keyboard       3.0   2000.0        NaN    KA  380001.0  1/14/2025            COD  Cancelled
112      1113     Kiran      Das     kiran.das@email.com      Tablet       1.0   1500.0  Hyderabad    GJ  500001.0  1/15/2025            COD    Pending
113      1114      Anil    Patel    anil.patel@email.com      Laptop       2.0      NaN  Ahmedabad    TN  110001.0  1/10/2025     NetBanking  Delivered
114      1115     Pooja    Patel   pooja.patel@email.com  Headphones       1.0      NaN    Kolkata    TN  500001.0  1/10/2025            UPI   Returned
115      1116     Pooja      Das     pooja.das@email.com       Mouse       NaN      NaN       Pune    GJ  380001.0  1/10/2025    Credit Card    Pending
116      1117     Pooja    Singh   pooja.singh@email.com      Tablet       3.0   2000.0  Hyderabad    WB  560001.0  1/10/2025            UPI    Pending
117      1118      Amit    Reddy                     NaN      Tablet       NaN  30000.0       Pune    MH  500001.0  1/19/2025            NaN    Pending
118      1119      Amit    Reddy    amit.reddy@email.com       Mouse       2.0   2000.0        NaN    KA  400001.0  1/20/2025    Credit Card    Pending
119      1120      Ravi      Das      ravi.das@email.com      Mobile       3.0   1500.0  Ahmedabad    GJ  500001.0  1/20/2025            UPI    Pending
120      1121     Pooja      Das     pooja.das@email.com  Headphones       3.0      NaN      Delhi    MH  110001.0  1/17/2025            NaN   Returned
121      1122      Ravi    Gupta    ravi.gupta@email.com  Headphones       1.0      NaN     Mumbai    TN  110001.0  1/18/2025     NetBanking    Pending
122      1123     Vikas    Patel   vikas.patel@email.com    Keyboard       3.0   1500.0  Hyderabad    TN  560001.0  1/17/2025     NetBanking   Returned
123      1124     Sneha    Kumar   sneha.kumar@email.com      Laptop       2.0  30000.0    Kolkata    MH       NaN  1/17/2025            UPI  Delivered
124      1125      Sita   Sharma   sita.sharma@email.com      Camera       2.0  55000.0     Mumbai    TN  110001.0  1/15/2025            COD  Delivered
125      1126     Rahul    Reddy   rahul.reddy@email.com  Headphones       3.0   1500.0      Delhi    TN  600001.0  1/20/2025    Credit Card  Delivered
126      1127      Anil      Das      anil.das@email.com    Keyboard       3.0      NaN  Hyderabad    DL  400001.0  1/18/2025            UPI  Cancelled
127      1128     Pooja    Reddy   pooja.reddy@email.com      Laptop       2.0   2000.0      Delhi    TN  560001.0  1/13/2025            COD    Pending
128      1129     Kiran    Mehta   kiran.mehta@email.com     Charger       1.0   1500.0    Chennai    TN  560001.0  1/20/2025     NetBanking   Returned
129      1130     Rahul    Verma   rahul.verma@email.com  Headphones       3.0      NaN        NaN    WB  560001.0  1/14/2025            UPI  Cancelled

In [30]:
print(data.head(3))

   order_id firstname lastname                  email   product  quantity  \
0      1001      Sita    Reddy   sita.reddy@email.com    Camera       2.0
1      1002      Sita     Nair                    NaN     Mouse       1.0
2      1003     Kiran    Mehta  kiran.mehta@email.com  Keyboard       1.0

     price       city state   pincode order_date payment_method     status
0   1500.0    Chennai    WB  500001.0  1/15/2025    Credit Card  Cancelled
1   2000.0  Bangalore    DL  600001.0  1/12/2025            NaN  Cancelled
2  55000.0      Delhi    TS  500001.0  1/19/2025            COD  Cancelled

In [32]:
print(data.tail(2))

     order_id firstname lastname                  email product  quantity  \
213      1060     Rahul    Kumar  rahul.kumar@email.com  Laptop       1.0
214      1061      Ravi      Das     ravi.das@email.com  Camera       3.0

       price       city state   pincode order_date payment_method     status
213  30000.0  Bangalore    GJ  400001.0  1/11/2025            UPI  Delivered
214   2000.0     Mumbai    GJ  500001.0  1/20/2025    Credit card    Pending

In [33]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        215 non-null    int64
 1   firstname       215 non-null    object
 2   lastname        215 non-null    object
 3   email           192 non-null    object
 4   product         215 non-null    object
 5   quantity        172 non-null    float64
 6   price           175 non-null    float64
 7   city            195 non-null    object
 8   state           215 non-null    object
 9   pincode         195 non-null    float64
 10  order_date      215 non-null    object
 11  payment_method  180 non-null    object
 12  status          215 non-null    object
dtypes: float64(3), int64(1), object(9)
memory usage: 22.0+ KB
None

In [34]:
print(data.describe())

          order_id    quantity         price        pincode
count   215.000000  172.000000    175.000000     195.000000
mean   1096.590698    2.063953  20800.000000  430821.512821
std      58.395285    0.852573  20899.595772  163607.348629
min    1001.000000    1.000000   1500.000000  110001.000000
25%    1046.500000    1.000000   1500.000000  380001.000000
50%    1094.000000    2.000000  30000.000000  500001.000000
75%    1147.500000    3.000000  30000.000000  560001.000000
max    1200.000000    3.000000  55000.000000  600001.000000

In [35]:
print(data.shape)

(215, 13)

In [36]:
print(data.dtypes)

order_id            int64
firstname          object
lastname           object
email              object
product            object
quantity          float64
price             float64
city               object
state              object
pincode           float64
order_date         object
payment_method     object
status             object
dtype: object

In [37]:
print(data.memory_usage())

Index              132
order_id          1720
firstname         1720
lastname          1720
email             1720
product           1720
quantity          1720
price             1720
city              1720
state             1720
pincode           1720
order_date        1720
payment_method    1720
status            1720
dtype: int64

In [38]:
print(data1)

      name   age
0     jain  23.0
1   ramana  21.0
2     neha   NaN
3   anusha   NaN
4  akshaya   NaN
5    akhil  88.0
6    priya   NaN

In [43]:
print(data1.isnull().sum())

name    0
age     4
dtype: int64

In [44]:
display(data1)

      name   age
0     jain  23.0
1   ramana  21.0
2     neha   NaN
3   anusha   NaN
4  akshaya   NaN
5    akhil  88.0
6    priya   NaN

In [45]:
data1['age']=data1['age'].fillna(21)

In [46]:
print(data1)

      name   age
0     jain  23.0
1   ramana  21.0
2     neha  21.0
3   anusha  21.0
4  akshaya  21.0
5    akhil  88.0
6    priya  21.0

In [52]:
d={
    'name':['jain','ramana','neha','anusha','akshaya','akhil','priya'],
    'age':[np.nan,21,np.nan,np.nan,np.nan,88,np.nan]
}

In [53]:
data2=pd.DataFrame(d)

In [54]:
data2

      name   age
0     jain   NaN
1   ramana  21.0
2     neha   NaN
3   anusha   NaN
4  akshaya   NaN
5    akhil  88.0
6    priya   NaN

In [55]:
data2['age']=data2['age'].ffill()

In [56]:
data2

      name   age
0     jain   NaN
1   ramana  21.0
2     neha  21.0
3   anusha  21.0
4  akshaya  21.0
5    akhil  88.0
6    priya  88.0

In [57]:
d={
    'name':['jain','ramana','neha','anusha','akshaya','akhil','priya'],
    'age':[np.nan,21,np.nan,np.nan,np.nan,88,np.nan]
}

In [58]:
data4=pd.DataFrame(d)

In [59]:
data4

      name   age
0     jain   NaN
1   ramana  21.0
2     neha   NaN
3   anusha   NaN
4  akshaya   NaN
5    akhil  88.0
6    priya   NaN

In [60]:
data4['age']=data4['age'].bfill()

In [61]:
data4

      name   age
0     jain  21.0
1   ramana  21.0
2     neha  88.0
3   anusha  88.0
4  akshaya  88.0
5    akhil  88.0
6    priya   NaN

In [62]:
data4['age']=data4['age'].ffill()

In [63]:
data4

      name   age
0     jain  21.0
1   ramana  21.0
2     neha  88.0
3   anusha  88.0
4  akshaya  88.0
5    akhil  88.0
6    priya  88.0

In [64]:
d={
    'name':['jain','ramana','neha','anusha','akshaya','akhil','priya'],
    'age':[np.nan,21,np.nan,np.nan,np.nan,88,np.nan]
}

In [65]:
data5=pd.DataFrame(d)

In [66]:
data5

      name   age
0     jain   NaN
1   ramana  21.0
2     neha   NaN
3   anusha   NaN
4  akshaya   NaN
5    akhil  88.0
6    priya   NaN

In [67]:
print(data5.dropna())

     name   age
1  ramana  21.0
5   akhil  88.0

In [68]:
d={
    'name':['jain','ramana','neha','anusha','akshaya','akhil','priya','jain','jain','ramana','ramana'],
    'age':[np.nan,21,np.nan,np.nan,np.nan,88,np.nan,24,np.nan,np.nan,21]
}

In [69]:
data6=pd.DataFrame(d)

In [70]:
data6

       name   age
0      jain   NaN
1    ramana  21.0
2      neha   NaN
3    anusha   NaN
4   akshaya   NaN
5     akhil  88.0
6     priya   NaN
7      jain  24.0
8      jain   NaN
9    ramana   NaN
10   ramana  21.0

In [73]:
print(data6.duplicated().sum())

2

In [74]:
data6

       name   age
0      jain   NaN
1    ramana  21.0
2      neha   NaN
3    anusha   NaN
4   akshaya   NaN
5     akhil  88.0
6     priya   NaN
7      jain  24.0
8      jain   NaN
9    ramana   NaN
10   ramana  21.0

In [75]:
data6=data6.drop_duplicates()

In [76]:
data6

      name   age
0     jain   NaN
1   ramana  21.0
2     neha   NaN
3   anusha   NaN
4  akshaya   NaN
5    akhil  88.0
6    priya   NaN
7     jain  24.0
9   ramana   NaN

In [77]:
data6['age']=data6['age'].fillna(21)

/tmp/ipykernel_11879/3453980209.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data6['age']=data6['age'].fillna(21)

In [78]:
data6

      name   age
0     jain  21.0
1   ramana  21.0
2     neha  21.0
3   anusha  21.0
4  akshaya  21.0
5    akhil  88.0
6    priya  21.0
7     jain  24.0
9   ramana  21.0

In [79]:
data6.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    9 non-null      object
 1   age     9 non-null      float64
dtypes: float64(1), object(1)
memory usage: 216.0+ bytes

In [83]:
data6['age']=data6['age'].astype(str)

/tmp/ipykernel_11879/3809361216.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data6['age']=data6['age'].astype(str)

In [84]:
data6

      name age
0     jain  21
1   ramana  21
2     neha  21
3   anusha  21
4  akshaya  21
5    akhil  88
6    priya  21
7     jain  24
9   ramana  21

In [85]:
data6.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    9 non-null      object
 1   age     9 non-null      object
dtypes: object(2)
memory usage: 216.0+ bytes

In [86]:
data6

      name age
0     jain  21
1   ramana  21
2     neha  21
3   anusha  21
4  akshaya  21
5    akhil  88
6    priya  21
7     jain  24
9   ramana  21

In [87]:
data6['name']=data6['name'].replace("jain","JAIN")

/tmp/ipykernel_11879/3175395044.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data6['name']=data6['name'].replace("jain","JAIN")

In [88]:
data6

      name age
0     JAIN  21
1   ramana  21
2     neha  21
3   anusha  21
4  akshaya  21
5    akhil  88
6    priya  21
7     JAIN  24
9   ramana  21

In [90]:
data6['age']=data6['age'].replace('21','25')

/tmp/ipykernel_11879/1309479174.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data6['age']=data6['age'].replace('21','25')

In [91]:
data6

      name age
0     JAIN  25
1   ramana  25
2     neha  25
3   anusha  25
4  akshaya  25
5    akhil  88
6    priya  25
7     JAIN  24
9   ramana  25